package handlers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"github.com/gin-gonic/gin"
	"github.com/Rohan0639/system-design-simulator/backend/models"
)

type xAIRequest struct {
	Model       string    `json:"model"`
	Messages    []Message `json:"messages"`
	Temperature float64   `json:"temperature"`
	ResponseFormat struct {
		Type string `json:"type"`
	} `json:"response_format"`
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type xAIResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
}

func GenerateDesign(c *gin.Context) {
	var input struct {
		Prompt string `json:"prompt"`
	}
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request payload"})
		return
	}

	apiKey := os.Getenv("GROK_API_KEY")
	endpoint := os.Getenv("XAI_ENDPOINT")
	if endpoint == "" {
		endpoint = "https://api.x.ai/v1/chat/completions"
	}

	if apiKey == "" {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "GROK_API_KEY is not set in environment"})
		return
	}

	log.Printf("Calling Grok with prompt: %s", input.Prompt)

	systemPrompt := `You are a System Design Architect. 
Return ONLY a valid JSON object. Do not include any markdown formatting or talk.
Allowed node types: client, load_balancer, api_server, database, cache, cdn, queue, storage.
Placement Logic (Absolute Coordinates):
- Clients: x=0, y=variable
- Entrance (CDN/LB): x=300, y=variable
- Processing (API): x=600, y=variable
- Storage/State (DB/Cache/Queue): x=900, y=variable

JSON Schema:
{
  "nodes": [{"id": "string", "type": "string", "label": "string", "capacity": number, "latency": number, "position": {"x": number, "y": number}}],
  "edges": [{"source": "string", "target": "string"}],
  "explanation": "string",
  "suggestions": ["string"]
}`

	reqBody := xAIRequest{
		Model: "llama-3.3-70b-versatile",
		Messages: []Message{
			{Role: "system", Content: systemPrompt},
			{Role: "user", Content: input.Prompt},
		},
		Temperature: 0.1,
	}
	reqBody.ResponseFormat.Type = "json_object"

	jsonData, _ := json.Marshal(reqBody)
	req, _ := http.NewRequest("POST", endpoint, bytes.NewBuffer(jsonData))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to connect to Grok API"})
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		log.Printf("Grok API Error (Status %d): %s", resp.StatusCode, string(body))
		c.JSON(resp.StatusCode, gin.H{"error": "Grok API error", "details": string(body)})
		return
	}

	var grokResp xAIResponse
	if err := json.NewDecoder(resp.Body).Decode(&grokResp); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to parse Grok response"})
		return
	}

	if len(grokResp.Choices) == 0 {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "No design generated by AI"})
		return
	}

	var finalGraph models.AIGeneratedGraph
	if err := json.Unmarshal([]byte(grokResp.Choices[0].Message.Content), &finalGraph); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "AI returned malformed JSON structure"})
		return
	}

	// Validate integrity
	if err := validateAIArchitecture(finalGraph); err != nil {
		c.JSON(http.StatusUnprocessableEntity, gin.H{"error": "AI generated invalid architecture", "details": err.Error()})
		return
	}

	log.Printf("Generated graph with %d nodes and %d edges", len(finalGraph.Nodes), len(finalGraph.Edges))
	c.JSON(http.StatusOK, finalGraph)
}

func validateAIArchitecture(g models.AIGeneratedGraph) error {
	nodeMap := make(map[string]bool)
	validTypes := map[string]bool{
		"client": true, "load_balancer": true, "api_server": true,
		"database": true, "cache": true, "cdn": true, "queue": true, "storage": true,
	}

	for _, n := range g.Nodes {
		if !validTypes[n.Type] {
			return fmt.Errorf("invalid node type: %s", n.Type)
		}
		nodeMap[n.ID] = true
	}

	for _, e := range g.Edges {
		if !nodeMap[e.Source] || !nodeMap[e.Target] {
			return fmt.Errorf("broken edge connection: %s -> %s", e.Source, e.Target)
		}
	}
	return nil
}
